// G:\quake2\baseq2\models/player_x/frames

#define SWING_CHOP			1
#define SWING_THRUST		2
#define SWING_UCUTRIGHT		3
#define SWING_UCUTLEFT		4
#define SWING_RIGHT			5
#define SWING_LEFT			6

#define BLOCK_RIGHT			7
#define BLOCK_LEFT			8
#define BLOCK_UPRIGHT		9
#define BLOCK_UPLEFT		10
#define BLOCK_UP			11
#define BLOCK_LOWRIGHT		12
#define BLOCK_LOWLEFT		13
#define BLOCK_LOW			14
#define SWING_SLICERIGHT	15
#define SWING_SLICELEFT		16
#define SWING_CROUCH_A		17
#define SWING_CROUCH_B		18
#define SWING_RUN_A			19
#define	SWING_RUN_B			20

#define SAB_blockltA		121
#define SAB_blockltB		125

#define SAB_blockrtA		121
#define SAB_blockrtB		125

#define SAB_blockultA		121
#define SAB_blockultB		125

#define SAB_blockurtA		121
#define SAB_blockurtB		125

#define SAB_blocklltA		121
#define SAB_blocklltB		125

#define SAB_blocklrtA		121
#define SAB_blocklrtB		125


#define SAB_chopA			121
#define SAB_chopB			125

#define SAB_sliceltA		121
#define SAB_sliceltB		125

#define SAB_slicertA		121
#define SAB_slicertB		125

#define SAB_swingltA		121
#define SAB_swingltB		125

#define SAB_swingrtA		126
#define SAB_swingrtB		130

#define SAB_ucutltA			136
#define SAB_ucutltB			140

#define SAB_ucutrtA			141
#define SAB_ucutrtB			144

#define SAB_thrustA			131
#define SAB_thrustB			135

//RipVTide
#define SAB_crouch1A		136
#define SAB_crouch1B		140

#define SAB_crouch2A		141
#define SAB_crouch2B		144

#define SAB_runsl1A			121
#define SAB_runsl1B			125

#define SAB_runsl2A			121
#define SAB_runsl2B			125

#define FRAME_ftransA		488
#define FRAME_ftransB		490

#define FRAME_fallingA		491
#define FRAME_fallingB		493

#define FRAME_impactA		493
#define FRAME_impactB		497

// This file generated by qdata - Do NOT Modify

#define FRAME_standgunA		0
#define FRAME_standgunB		6

#define FRAME_reloadA		7
#define FRAME_reloadB		18

#define FRAME_rungunA		19
#define FRAME_rungunB		24

#define FRAME_attackgunA	25
#define FRAME_attackgunB	28

#define FRAME_throwA		29
#define FRAME_throwB		33

#define FRAME_paingunA		34
#define FRAME_paingunB		36

#define FRAME_paingun2A		37
#define FRAME_paingun2B		40

#define FRAME_lightpainA	41
#define FRAME_lightpainB	44

#define FRAME_chokepainA	45
#define FRAME_chokepainB	49

#define FRAME_jumpgun1		50
#define FRAME_jumpgun2		51
#define FRAME_jumpgun3		52
#define FRAME_jumpgun4		53
#define FRAME_jumpgun5		54
#define FRAME_jumpgun6		55

#define FRAME_backflipA		56
#define FRAME_backflipB		62

#define FRAME_forwardflipA	63
#define FRAME_forwardflipB	69

#define FRAME_forceA		70
#define FRAME_forceB		81

#define FRAME_forceinA		70
#define FRAME_forceinB		81

#define FRAME_forcelpA		72
#define FRAME_forcelpB		75

#define FRAME_forcechinA	76
#define FRAME_forcechinB	81

#define FRAME_forcechA		78
#define FRAME_forcechB		81

#define FRAME_holsterA		82
#define FRAME_holsterB		87

#define FRAME_unholsterA	92
#define FRAME_unholsterB	97

#define FRAME_crstndA		98
#define FRAME_crstndB		104

#define FRAME_crwalkA		105
#define FRAME_crwalkB		110

#define FRAME_crforceA		111
#define FRAME_crforceB		122

#define FRAME_crattakA		123
#define FRAME_crattakB		127

#define FRAME_crpainA		128
#define FRAME_crpainB		131

#define FRAME_standgun2A	132
#define FRAME_standgun2B	138

#define FRAME_rungun2A		139
#define FRAME_rungun2B		144

#define FRAME_firegun2A		145
#define FRAME_firegun2B		148


//Light Saber

#define FRAME_lightsbrA		235
#define FRAME_lightsbrB		238

#define FRAME_standsbrA		239
#define FRAME_standsbrB		245

#define FRAME_walksbrA		246
#define FRAME_walksbrB		253

#define FRAME_runsbrA		254
#define FRAME_runsbrB		259

#define FRAME_chopA			260
#define FRAME_chopB			264

#define FRAME_thrustA		265
#define FRAME_thrustB		270

#define FRAME_upprcutlftA	271
#define FRAME_upprcutlftB	277

#define FRAME_upprcutrtA	278
#define FRAME_upprcutrtB	284

#define FRAME_swinglftA		285
#define FRAME_swinglftB		291

#define FRAME_swingrtA		292
#define FRAME_swingrtB		298

#define FRAME_slicelftA		299
#define FRAME_slicelftB		305

#define FRAME_slicertA		306
#define FRAME_slicertB		312

#define FRAME_b_upleftA		313
#define FRAME_b_upleftB		318

#define FRAME_b_uprightA	319
#define FRAME_b_uprightB	324

#define FRAME_b_leftA		325
#define FRAME_b_leftB		330

#define FRAME_b_rightA		331
#define FRAME_b_rightB		336

#define FRAME_b_lowleftA	337
#define FRAME_b_lowleftB	342

#define FRAME_b_lowrightA	343
#define FRAME_b_lowrightB	348

#define FRAME_e_crouch1A	349
#define FRAME_e_crouch1B	353

#define FRAME_e_crouch2A	354
#define FRAME_e_crouch2B	358

#define FRAME_e_runsl1A		359
#define FRAME_e_runsl1B		363

#define FRAME_e_runsl2A		364
#define FRAME_e_runsl2B		368

//no weapon

#define FRAME_nWEPA			82
#define FRAME_nWEPB			89

#define FRAME_cWEPA			90
#define FRAME_cWEPB			97

#define FRAME_standA		385
#define FRAME_standB		393

#define FRAME_walkA			394
#define FRAME_walkB			401

#define FRAME_runA			402
#define FRAME_runB			407

#define FRAME_swdeathA		408
#define FRAME_swdeathB		414

#define FRAME_crdeathA		415
#define FRAME_crdeathB		420

#define FRAME_death1A		421
#define FRAME_death1B		427

#define FRAME_death2A		428
#define FRAME_death2B		436

#define FRAME_death3A		437
#define FRAME_death3B		444

#define FRAME_chokedeathA	445
#define FRAME_chokedeathB	460

#define	FRAME_noheadA		461
#define	FRAME_noheadB		469

#define	FRAME_rightarmA		470
#define	FRAME_rightarmB		478

#define	FRAME_leftarmA		479
#define	FRAME_leftarmB		487

//SWIM

#define FRAME_swstandA		149
#define FRAME_swstandB		155

#define FRAME_swforwardA	156
#define FRAME_swforwardB	161

#define FRAME_swbackA		162
#define FRAME_swbackB		167

#define FRAME_swattackA		168
#define FRAME_swattackB		171

//#define FRAME_swsaberA		372
//#define FRAME_swsaberB		377

#define FRAME_swpainA		172
#define FRAME_swpainB		174

//#define FRAME_sbrthrowA		381
//#define FRAME_sbrthrowB		391

#define FRAME_padA			224
#define FRAME_padB			230

//CROUCH

#define FRAME_crouchsbrA	98
#define FRAME_crouchsbrB	104

#define FRAME_crouchfinA	111
#define FRAME_crouchfinB	116

#define FRAME_crouchflpA	113
#define FRAME_crouchflpB	116

#define FRAME_crouchfchinA	117
#define FRAME_crouchfchinB	122

#define FRAME_crouchfchlpA	119
#define FRAME_crouchfchlpB	122

//

#define	FRAME_flashwepA		175
#define	FRAME_flashwepB		190

#define	FRAME_flashsbrA		369
#define	FRAME_flashsbrB		384

#define	FRAME_gobystA		191
#define	FRAME_gobystB		194

#define	FRAME_bystandA		195
#define	FRAME_bystandB		201

#define	FRAME_bytalkA		202
#define	FRAME_bytalkB		216

#define	FRAME_byswitchA		217
#define	FRAME_byswitchB		223

#define	FRAME_bypadA		224
#define	FRAME_bypadB		230

#define	FRAME_byendA		231
#define	FRAME_byendB		234

#define MODEL_SCALE			1.000000
