// G:\quake2\baseq2\models/monsters/soldier

// This file generated by ModelGen - Do NOT Modify

#define FRAME_stand01		0
#define FRAME_stand02		1
#define FRAME_stand03		2
#define FRAME_stand04		3
#define FRAME_stand05		4
#define FRAME_stand06		5
#define FRAME_stand07		6
#define FRAME_stand08		7
#define FRAME_stand09		8
#define FRAME_stand10		9
#define FRAME_stand11		10
#define FRAME_stand12		11
#define FRAME_stand13		12
#define FRAME_stand14		13
#define FRAME_stand15		14
#define FRAME_stand16		15
#define FRAME_stand17		16
#define FRAME_stand18		17
#define FRAME_stand19		18
#define FRAME_stand20		19
#define FRAME_stand21		20
#define FRAME_stand22		21
#define FRAME_stand23		22
#define FRAME_stand24		23
#define FRAME_stand25		24
#define FRAME_stand26		25
#define FRAME_stand27		26
#define FRAME_walk01		27
#define FRAME_walk02		28
#define FRAME_walk03		29
#define FRAME_walk04		30
#define FRAME_walk05		31
#define FRAME_walk06		32
#define FRAME_walk07		33
#define FRAME_walk08		34
#define FRAME_walk09		35
#define FRAME_walk10		36
#define FRAME_walk11		37
#define FRAME_walk12		38
#define FRAME_walk13		39
#define FRAME_walk14		40
#define FRAME_walk15		41
#define FRAME_walk16		42
#define FRAME_walk17		43
#define FRAME_walk18		44
#define FRAME_walk19		45
#define FRAME_walk20		46
#define FRAME_walk21		47
#define FRAME_walk22		48
#define FRAME_walk23		49
#define FRAME_walk24		50
#define FRAME_walk25		51
#define FRAME_walk26		52
#define FRAME_walk27		53
#define FRAME_walk28		54
#define FRAME_snap01		55
#define FRAME_snap02		56
#define FRAME_snap03		57
#define FRAME_snap04		58
#define FRAME_snap05		59
#define FRAME_stand1		60
#define FRAME_run01		61
#define FRAME_run02		62
#define FRAME_run03		63
#define FRAME_run04		64
#define FRAME_run05		65
#define FRAME_run06		66
#define FRAME_run07		67
#define FRAME_run08		68
#define FRAME_run09		69
#define FRAME_run10		70
#define FRAME_run11		71
#define FRAME_run12		72
#define FRAME_run13		73
#define FRAME_run14		74
#define FRAME_run15		75
#define FRAME_run16		76
#define FRAME_run17		77
#define FRAME_run18		78
#define FRAME_fire01	79
#define FRAME_fire02	80
#define FRAME_fire03	81
#define FRAME_fire04	82
#define FRAME_pain01	83
#define FRAME_pain02	84
#define FRAME_pain03	85
#define FRAME_pain04	86
#define FRAME_duckA		87
#define FRAME_duck3		88
#define FRAME_duck4		89
#define FRAME_duckB		92

#define FRAME_death01		0
#define FRAME_death33		32

#define MODEL_SCALE		1.000000


/*footstep frames
walk06		32
walk12		38
walk18		44
walk24		50

run5		65
run9		69
run13		73
*/
