// G:\quake2\baseq2\models/player_y

// This file generated by ModelGen - Do NOT Modify

#define	FRAME_stand01	0
#define	FRAME_stand11	10

#define	FRAME_walk101	11
#define	FRAME_walk110 	20
#define	FRAME_walk211	21
#define	FRAME_walk220 	31
#define	FRAME_walk221	32
#define	FRAME_walk322	33
#define	FRAME_walk327 	37

#define	FRAME_snap01	38
#define	FRAME_snap03	40

#define	FRAME_work01	41
#define	FRAME_work10	50

#define	FRAME_run01		52
#define	FRAME_run08		59

#define	FRAME_death01	60
#define	FRAME_death16	75

#define MODEL_SCALE		1.000000
