// G:\quake2\baseq2\models/player_y

// This file generated by ModelGen - Do NOT Modify

#define FRAME_slackingA		0
#define FRAME_slackingB		3

#define FRAME_sleepA		4
#define FRAME_sleepB		8

#define FRAME_awakeA		9
#define FRAME_awakeB		12

#define FRAME_fidgetA		13
#define FRAME_fidgetB		22

#define FRAME_walkA			23
#define FRAME_walkB			40

#define FRAME_runA			41
#define FRAME_runB			46

#define FRAME_maskonA		47
#define FRAME_maskonB		52

#define FRAME_maskoffA		53
#define FRAME_maskoffB		58

#define FRAME_workwallA		59
#define FRAME_workwallB		69

#define FRAME_workgrndA		70
#define FRAME_workgrndB		80

#define FRAME_painworkA		81
#define FRAME_painworkB		85

#define FRAME_talkA			86
#define FRAME_talkB			100

#define FRAME_listenA		101
#define FRAME_listenB		112

#define FRAME_agreeA		113
#define FRAME_agreeB		119

#define FRAME_disagreeA		120
#define FRAME_disagreeB		134

#define FRAME_readyfightA		135
#define FRAME_readyfightB		145

#define FRAME_painA			146
#define FRAME_painB			149

#define FRAME_painbA		150
#define FRAME_painbB		153

#define FRAME_lightpainA		154
#define FRAME_lightpainB		156

#define FRAME_chokepainA		157
#define FRAME_chokepainB		161

#define FRAME_swingA		162
#define FRAME_swingB		169

#define FRAME_swingbigA		170
#define FRAME_swingbigB		180

#define FRAME_cowerA		181
#define FRAME_cowerB		193

#define FRAME_cowerfidgetA		194
#define FRAME_cowerfidgetB		202

#define FRAME_cowerpainA		203
#define FRAME_cowerpainB		206

#define FRAME_cowerrunA		207
#define FRAME_cowerrunB		212

#define FRAME_dieA			213
#define FRAME_dieB			219

#define FRAME_diebA			220
#define FRAME_diebB			237

#define FRAME_chokedieA		238
#define FRAME_chokedieB		250








#define MODEL_SCALE		1.000000
