// G:\quake2\baseq2\models/player_y

// This file generated by ModelGen - Do NOT Modify

#define	FRAME_stand01	0
#define	FRAME_stand11	10

#define	FRAME_walk101	11
#define	FRAME_walk110 	20
#define	FRAME_walk211	21
#define	FRAME_walk220 	31
#define	FRAME_walk221	32
#define	FRAME_walk322	33
#define	FRAME_walk327 	37

#define	FRAME_snap01	38
#define	FRAME_snap13	50

#define	FRAME_stand201	51

#define	FRAME_attack01	52
#define	FRAME_attack04	55

#define	FRAME_run01		56
#define	FRAME_run08		63

#define	FRAME_death01	64
#define	FRAME_death16	79

#define MODEL_SCALE		1.000000
