// Generated by ModelEd
#define ACTION_nothing			0
#define ACTION_attack1			1
#define ACTION_attack2			2
#define ACTION_run				3
#define ACTION_walk				4

#define FRAME_stand1	0
#define FRAME_spin1		1
#define FRAME_spin2		2
#define FRAME_spin3		3
#define FRAME_spin4		4
#define FRAME_spin5		5
#define FRAME_pain1		6
#define FRAME_pain2		7
#define FRAME_pain3		8
#define FRAME_pain4		9
#define FRAME_pain5		10
#define FRAME_map		11

#define MODEL_SCALE		1.000000
