// Generated by ModelEd

//#define ACTION_nothing			0
//#define ACTION_attack1			1

#define FRAME_stand1	0
#define FRAME_attack1	1
#define FRAME_attack2	2
#define FRAME_attack3	3
#define FRAME_attack4	4
#define FRAME_attack5	5
#define FRAME_map	6

#define MODEL_SCALE	1.000000
