/* ANNIHILATION QUAKE 2 */
/* *** ALLOW FLAGS *** */
#define ANN_ALLOW_RICOCHETBLASTER              1
#define ANN_ALLOW_SHOTGUN                      2
#define ANN_ALLOW_AUTOSHOTGUN                  4
#define ANN_ALLOW_SUPERSHOTGUN                 8
#define ANN_ALLOW_MACHINEGUN                  16
#define ANN_ALLOW_CHAINGUN                    32
#define ANN_ALLOW_GRENADELAUNCHER             64
#define ANN_ALLOW_CLUSTERGRENADE             128
#define ANN_ALLOW_FLARE                      256
#define ANN_ALLOW_ROCKETLAUNCHER             512
#define ANN_ALLOW_BOUNCEMISSILE             1024
#define ANN_ALLOW_HOMINGMISSILE             2048
#define ANN_ALLOW_GUIDEDMISSILE             4096
#define ANN_ALLOW_NUKE                      8192
#define ANN_ALLOW_HYPERBLASTER             16384
#define ANN_ALLOW_LASERBLASTER             32768
#define ANN_ALLOW_FREEZER                  65536
#define ANN_ALLOW_RAILGUN                 131072
#define ANN_ALLOW_SNIPERRIFLE             262144
#define ANN_ALLOW_BFG10K                  524288
#define ANN_ALLOW_PHASER                 1048576
#define ANN_ALLOW_HANDGRENADE            2097152
#define ANN_ALLOW_PIPEBOMB               4194304
#define ANN_ALLOW_PROXIMITYMINE          8388608

#define ANN_ALLOW2_PAUSE                       1
#define ANN_ALLOW2_KAMIKAZE                    2
#define ANN_ALLOW2_FAKEDEATH                   4
#define ANN_ALLOW2_CLOAKING                    8
#define ANN_ALLOW2_CLOAKINGJAMMER             16
#define ANN_ALLOW2_TELEPORTER                 32
#define ANN_ALLOW2_ANTIGRAVBOOTS              64
#define ANN_ALLOW2_DEFENCELASER              128
#define ANN_ALLOW2_AIRSTRIKE                 256
#define ANN_ALLOW2_LASERDRONE                512
#define ANN_ALLOW2_TORTURECHAMBER           1024
#define ANN_ALLOW2_CONVERT					2048
#define ANN_ALLOW2_RADAR				    4096
#define ANN_ALLOW2_DISRUPTOR				8192
#define ANN_ALLOW2_FLASHLIGHT			   16384
#define ANN_ALLOW2_IRGOGGLES			   32768
#define ANN_ALLOW2_RADARHIDECLOAKERS       65536
#define ANN_ALLOW2_LIGHTSABER             131072
#define ANN_ALLOW2_REGENCELLS             262144

extern	cvar_t	*ann_allow;
extern	cvar_t	*ann_allow2;
/* *** */

