// Maj++----------------------------------
// New item types

// Item Ammo (IT_AMMO)
gitem_t 
//		*item_shells,
        *item_cells,
        *item_rockets,
        *item_grenades,
        *item_slugs,
        *item_bullets,

// Item Weapons (IT_WEAPON)
        *item_proxmine,
        *item_slapper,
        *item_blaster,
        *item_shotgun,
        *item_machinegun,
        *item_supershotgun,
        *item_chaingun,
        *item_handgrenade,
        *item_grenadelauncher,
        *item_rocketlauncher,
        *item_hyperblaster,
        *item_railgun,
        *item_bfg,

// Item Armor (IT_ARMOR)
        *item_jacketarmor,
        *item_combatarmor,
        *item_bodyarmor,
        *item_armorshard,
        *item_powerscreen,
        *item_powershield,

// Item Health (IT_HEALTH)
        *item_adrenaline,
        *item_health,
        *item_stimpak,
        *item_health_large,
        *item_health_mega,

// Item Powerup (IT_POWERUP)
        *item_quad,
        *item_invulnerability,
        *item_silencer,
        *item_breather,
        *item_enviro,

// Item Pak (IT_PACK)
        *item_pack,
        *item_bandolier,

// Item Nodes (IT_NODE)
        *item_navi1,
        *item_navi2,
        *item_navi3;
        