// Feature Bans

#define	FEATUREBAN_FLASHLIGHT			1
#define FEATUREBAN_HOOK					2
#define FEATUREBAN_CLONESHIELD			4
#define FEATUREBAN_ARTILLERY			8
#define FEATUREBAN_TELEPUDDLE			16

// Blaster Bans

#define	BLASTERBAN_BATTERYOPERATEDDRILL	1
#define BLASTERBAN_SAWTOOTHEDHAMMER		2
#define BLASTERBAN_SCREWDRIVER			4
#define BLASTERBAN_RADIODETONATOR		8
#define BLASTERBAN_NEUTRONBLASTER		16
#define BLASTERBAN_CHAINFIST			32
#define BLASTERBAN_GRAPPLE				64

// Shotgun Bans

#define	SHOTGUNBAN_CO2CANNON			1
#define SHOTGUNBAN_SHARDCANNON			2
#define SHOTGUNBAN_MAGNET				4

// Super Shotgun Bans

#define	SSGBAN_TOXICGASGUN				1
#define SSGBAN_DISKLAUNCHER				2
#define SSGBAN_BLADERUNNER				4

// Machinegun Bans

#define	MACHINEGUNBAN_RICOCHET			1
#define MACHINEGUNBAN_NEEDLER			2
#define MACHINEGUNBAN_ETFRIFLE			4
#define MACHINEGUNBAN_STAPLER			8

// Chaingun Bans

#define	CHAINGUNBAN_CHAINGRENADE		1
#define CHAINGUNBAN_FIREFLY				2
#define CHAINGUNBAN_CONFUZZLER			4

// Grenade Launcher Bans

#define	GLBAN_NAPALMJUMPINGBEANS	1
#define GLBAN_NAPALMLAUNCHER		2
#define GLBAN_BALLOONLAUNCHER		4
#define GLBAN_RUBBERBALLS			8
#define GLBAN_BASKETBALL			16
#define GLBAN_BEACHBALL				32
#define GLBAN_PROXLAUNCHER			64

// Grenade Bans

#define	GRENADEBAN_GRAVITY			1
#define GRENADEBAN_CONCUSSION		2
#define GRENADEBAN_INFEST			4
#define GRENADEBAN_ROTATINGLASER	8
#define GRENADEBAN_AREA				16
#define GRENADEBAN_EXPLODINGJACK	32
#define GRENADEBAN_FLASH			64
#define	GRENADEBAN_GLOWSTICKS		128
#define GRENADEBAN_GIBMINES			256
#define GRENADEBAN_SPIKEGRENADE		512
#define GRENADEBAN_EARTHQUAKE		1024
#define GRENADEBAN_LASERLINK		2048
#define GRENADEBAN_TRAP				4096
#define GRENADEBAN_TESLA			8192
#define GRENADEBAN_TELEPORT			16384
#define GRENADEBAN_CHAINLIGHTNING	32768
#define GRENADEBAN_LASERTRAP		32768*2

// Rocket Launcher Bans

#define	RLBAN_FREEZENUKE		1
#define RLBAN_GRAVITYMISSILE	2
#define RLBAN_WOMD				4
#define RLBAN_FOOBY				8
#define RLBAN_DEVASTATOR		16
#define RLBAN_ROCKETPODS		32
#define RLBAN_ACCELLEROCKET		64
#define	RLBAN_PACMAN			128
#define RLBAN_DISRUPTOR			256
#define RLBAN_BLOCKCANNON			512

// Hyperblaster Bans

#define	HYPERBLASTERBAN_PLASMA		1
#define HYPERBLASTERBAN_BEES		2
#define HYPERBLASTERBAN_FIREHOSE	4
#define HYPERBLASTERBAN_HEATLASER	8
#define HYPERBLASTERBAN_PLASMABEAM	16
#define HYPERBLASTERBAN_IONRIPPER	32
#define HYPERBLASTERBAN_PINGGUN		64

// Railgun Bans

#define	RAILGUNBAN_RICOCHET		1
#define RAILGUNBAN_TRIPLESLUG	2
#define RAILGUNBAN_THUNDERBOLT	4
#define RAILGUNBAN_PHALANX		8
#define RAILGUNBAN_BEAMCANNON	16

// BFG10k Bans

#define	BFGBAN_LIGHTNINGCLOUD	1
#define BFGBAN_ACIDCLOUD		2
#define BFGBAN_VOLCANO			4
#define BFGBAN_SOUNDWAVE		8
#define BFGBAN_NEUTRON			16
#define BFGBAN_PIG2K			32
#define BFGBAN_GRAVITY			64

// Item bans

#define ITEMBAN_TRANSPARENCY_DEVICE 1
#define ITEMBAN_DEFLECTOR_SHIELD	2
#define ITEMBAN_IR_GOGGLES			4
#define ITEMBAN_JUMP_BOOTS			8
#define ITEMBAN_DONKEY_KONG_HAMMER	16
#define ITEMBAN_STARMAN				32
#define ITEMBAN_MAGIC_CARPET		64
#define ITEMBAN_REGENERATION		128
#define ITEMBAN_TESLACOIL   		128

qboolean CheckBan (cvar_t *cvar, int value);
