int anti_lpb(edict_t *, edict_t *, int);
int pro_hpb(edict_t *, edict_t *, int);
void protecthpb(edict_t *, edict_t *);
qboolean lagged_out(edict_t *);
qboolean pent_from_lag(edict_t *);
int lag_sickness(edict_t *);
qboolean lag_msg(edict_t *t);
qboolean short_lag_msg(edict_t *t);
qboolean lag_sick_notice(edict_t *t);
void do_bop_frame(edict_t *);
void do_greeting(edict_t *);
void get_mode_name(char *gmstr);
void bopinit();
void check_effects(edict_t *);
qboolean bop_showicon(edict_t *);
void check_4_lagpent(edict_t *, edict_t *);
qboolean adjust_resistance(edict_t *, edict_t *, int *);
void reset_bop_counters();
void bophelp(edict_t *);
void refresh_bop_menu(edict_t *);
void adv_bop_menu(edict_t *);
void bopreport(edict_t *);
qboolean bop_client_cmds(edict_t *, char *, char *);
qboolean process_bop_cmds(char *, char *);
void sv_gamemode();
void sv_laghelp_str();
void sv_laghelp_rst();
void sv_nobophelp();
void sv_bopsickremove();
void sv_laghelp_old();
void sv_lagcap_str();
void sv_lagcap_rst();
void sv_pingmax();
void sv_pingmin();
void sv_lagbare();
void sv_lagpent();
void sv_lagsick();
void sv_lagpeak();
void sv_lagtimeout();
void sv_lagsuicide();
void sv_lagslag();
void sv_verbose();
void sv_invisible();
void sv_bopmanageobservers();
void Cmd_lagstats(edict_t *);
float getargf();
void LagObituary (edict_t *self, edict_t *inflictor, edict_t *attacker);
