// Generated by ModelEd

#define FRAME_stand1	0
#define FRAME_stand2	1
#define FRAME_stand3	2
#define FRAME_attack1	3
#define FRAME_attack2	4
#define FRAME_attack3	5
#define FRAME_attack4	6
#define FRAME_attack5	7
#define FRAME_attack6	8
#define FRAME_attack7	9
#define FRAME_pain1		10
#define FRAME_pain2		11
#define FRAME_pain3		12
#define FRAME_pain4		13
#define FRAME_walk1		14
#define FRAME_walk2		15
#define FRAME_walk3		16
#define FRAME_walk4		17
#define FRAME_walk5		18
#define FRAME_death1	19
#define FRAME_death2	20
#define FRAME_death3	21
#define FRAME_death4	22
#define FRAME_death5	23
#define FRAME_death6	24
#define FRAME_death7	25

#define MODEL_SCALE	1.000000