// Generated by ModelEd

#define FRAME_stand1	0
#define FRAME_stand2	1
#define FRAME_stand3	2
#define FRAME_walk1	3
#define FRAME_walk2	4
#define FRAME_walk3	5
#define FRAME_walk4	6
#define FRAME_walk5	7
#define FRAME_pain1	8
#define FRAME_pain2	9
#define FRAME_attack1	10
#define FRAME_attack2	11
#define FRAME_attack3	12
#define FRAME_attack4	13
#define FRAME_attack5	14
#define FRAME_attack6	15
#define FRAME_attack7	16
#define FRAME_death0	17
#define FRAME_death1	18
#define FRAME_death2	19
#define FRAME_death3	20
#define FRAME_death4	21
#define FRAME_death5	22
#define FRAME_death6	23
#define FRAME_death7	24
#define FRAME_death8	25

#define MODEL_SCALE	1.000000