// Generated by ModelEd

#define FRAME_stand1	0
#define FRAME_stand2	1
#define FRAME_stand3	2
#define FRAME_stand4	3
#define FRAME_stand5	4
#define FRAME_stand6	5
#define FRAME_stand7	6
#define FRAME_stand8	7
#define FRAME_stand9	8
#define FRAME_stand10	9
#define FRAME_walk1		10
#define FRAME_walk2		11
#define FRAME_walk3		12
#define FRAME_walk4		13
#define FRAME_walk5		14
#define FRAME_walk6		15
#define FRAME_walk7		16
#define FRAME_pain1		17
#define FRAME_pain2		18
#define FRAME_pain3		19
#define FRAME_pain4		20
#define FRAME_attack1	21
#define FRAME_attack2	22
#define FRAME_attack4	23
#define FRAME_attack5	24
#define FRAME_attack6	25
#define FRAME_death1	26
#define FRAME_death2	27
#define FRAME_death3	28
#define FRAME_death4	29
#define FRAME_death5	30
#define FRAME_death6	31
#define FRAME_death7	32
#define FRAME_death8	33

#define MODEL_SCALE	1.000000