// Generated by ModelEd

#define FRAME_stand1	0
#define FRAME_stand2	1
#define FRAME_stand3	2
#define FRAME_stand4	3
#define FRAME_stand5	4
#define FRAME_stand6	5
#define FRAME_pain1		6
#define FRAME_pain2		7
#define FRAME_pain3		8
#define FRAME_pain4		9
#define FRAME_attack1	10
#define FRAME_attack2	11
#define FRAME_attack3	12
#define FRAME_attack4	13
#define FRAME_attack5	14

#define MODEL_SCALE	1.000000