// Generated by ModelEd

#define FRAME_stand1	0
#define FRAME_stand2	1
#define FRAME_stand3	2
#define FRAME_stand4	3
#define FRAME_stand5	4
#define FRAME_stand6	5
#define FRAME_walk1		6
#define FRAME_walk2		7
#define FRAME_walk3		8
#define FRAME_walk4		9
#define FRAME_walk5		10
#define FRAME_walk6		11
#define FRAME_walk7		12
#define FRAME_walk8		13
#define FRAME_attack1	14
#define FRAME_attack2	15
#define FRAME_attack3	16
#define FRAME_attack4	17
#define FRAME_attack5	18
#define FRAME_pain1		19
#define FRAME_pain2		20
#define FRAME_pain3		21
#define FRAME_pain4		22
#define FRAME_pain5		23
#define FRAME_death1	24
#define FRAME_death2	25
#define FRAME_death3	26
#define FRAME_death4	27
#define FRAME_death5	28
#define FRAME_death6	29

#define MODEL_SCALE	1.000000