// Generated by ModelEd

#define FRAME_stand1	0
#define FRAME_stand2	1
#define FRAME_stand3	2
#define FRAME_stand4	3
#define FRAME_pain1	4
#define FRAME_pain2	5
#define FRAME_pain3	6
#define FRAME_attack1	7
#define FRAME_attack2	8
#define FRAME_attack3	9
#define FRAME_attack4	10
#define FRAME_attack5	11
#define FRAME_attack6	12
#define FRAME_attack7	13
#define FRAME_death1	14
#define FRAME_death2	15
#define FRAME_death3	16
#define FRAME_death4	17
#define FRAME_death5	18
#define FRAME_death6	19

#define MODEL_SCALE	1.000000