// Generated by ModelEd


#define FRAME_punch01	198
#define FRAME_punch02	199
#define FRAME_punch03	200
#define FRAME_punch04	201
#define FRAME_punch05	202
#define FRAME_punch06	203
#define FRAME_punch07	204
#define FRAME_punch08	205
#define FRAME_punch09	206
#define FRAME_punch10	207
#define FRAME_crpunch1	208
#define FRAME_crpunch2	209
#define FRAME_crpunch3	210
#define FRAME_crpunch4	211
#define FRAME_crpunch5	212
