// Generated by ModelEd

#define FRAME_fly1		0
#define FRAME_fly2		1
#define FRAME_fly3		2	
#define FRAME_fly4		3
#define FRAME_fly5		4
#define FRAME_fly6		5
#define FRAME_fly7		6
#define FRAME_fly8		7
#define FRAME_fly9		8
#define FRAME_fly10		9
#define FRAME_fly11		10
#define FRAME_fly12		11
#define FRAME_fly13		12
#define FRAME_fly14		13
#define FRAME_pain1		14
#define FRAME_pain2		15
#define FRAME_pain3		16
#define FRAME_attack1	17
#define FRAME_attack2	18
#define FRAME_attack3	19
#define FRAME_attack4	20
#define FRAME_attack5	21
#define FRAME_attack6	22
#define FRAME_attack7	23
#define FRAME_attack8	24

#define MODEL_SCALE	1.000000 